site_name: api
site_description: base api
repo_url: https://github.com/unknowncoder05/NodesApi
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/unknowncoder05">unknowncoder05</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
