# Generated by Django 4.0.4 on 2022-06-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_sub_alter_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sub',
            new_name='auth0_id',
        ),
        migrations.AddField(
            model_name='user',
            name='auth0_identity_provider',
            field=models.CharField(choices=[('GO', 'google-oauth2')], default='GO', max_length=2),
        ),
    ]
