# Generated by Django 4.0.4 on 2022-06-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_sub_user_auth0_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth0_identity_provider',
        ),
    ]
