# Generated by Django 4.0.4 on 2022-07-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_feed_alter_node_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='parents',
        ),
    ]
