# Generated by Django 4.0.4 on 2022-08-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_remove_node_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='type',
        ),
        migrations.AlterField(
            model_name='proposedrelationship',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_nodes', to='nodes.node'),
        ),
        migrations.AlterField(
            model_name='proposedrelationship',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_nodes', to='nodes.node'),
        ),
    ]
